<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-2P2KGHCT" failures="2" tests="7" name="Test" time="0.05" errors="0" timestamp="2023-07-21T01:53:52 IST">
  <testcase classname="Failed_test.demo" name="Test1" time="0.007"/>
  <testcase classname="Failed_test.demo" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Failed_test.demo" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Failed_test.demo" name="Test2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Failed_test.demo.Test2(demo.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="Failed_test.demo" name="Test3" time="0.001">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="Failed_test.demo" name="Test3" time="0.0">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="Failed_test.demo" name="Test3" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Failed_test.demo.Test3(demo.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
</testsuite> <!-- Test -->
