<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-2P2KGHCT" failures="2" tests="2" name="Default test(failed)" time="0.073" errors="0" timestamp="2023-07-12T15:54:16 IST">
  <testcase classname="Failed_test.demo" name="Test2" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Failed_test.demo.Test2(demo.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="Failed_test.demo" name="Test3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Failed_test.demo.Test3(demo.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="Failed_test.demo" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Default test(failed) -->
